#pragma once

#define PARTIX_VIEW_UBO_BINDING_POINT 0
#define PARTIX_EMITTER_UBO_BINDING_POINT 1
#define PARTIX_ATOMIC_BUFFERr_BINDING_POINT 0
#define PARTIX_SSBO_BINDING_POINT0 1
#define PARTIX_SSBO_BINDING_POINT1 2